# Generated by Django 4.0.4 on 2022-05-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(null=True, upload_to='%Y/%m'),
        ),
    ]
